/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuizId = IDL.Nat;
export const Question = IDL.Record({
  'correctIndex' : IDL.Nat,
  'prompt' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QuizStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const Quiz = IDL.Record({
  'id' : QuizId,
  'status' : QuizStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'questions' : IDL.Vec(Question),
});
export const QuestionOutput = IDL.Record({
  'prompt' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Timestamp = IDL.Int;
export const Submission = IDL.Record({
  'answers' : IDL.Vec(IDL.Nat),
  'participantName' : IDL.Text,
  'score' : IDL.Nat,
  'correctAnswers' : IDL.Vec(IDL.Nat),
  'timestamp' : Timestamp,
  'quizId' : QuizId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestion' : IDL.Func([QuizId, Question], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createQuiz' : IDL.Func([IDL.Text, IDL.Text], [QuizId], []),
  'deleteQuiz' : IDL.Func([QuizId], [], []),
  'getAllQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPublishedQuizzes' : IDL.Func([], [IDL.Vec(QuizId)], ['query']),
  'getQuiz' : IDL.Func([QuizId], [Quiz], ['query']),
  'getQuizForTaking' : IDL.Func([QuizId], [IDL.Vec(QuestionOutput)], ['query']),
  'getQuizSubmissions' : IDL.Func([QuizId], [IDL.Vec(Submission)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishQuiz' : IDL.Func([QuizId], [], []),
  'submitAnswers' : IDL.Func(
      [IDL.Text, QuizId, IDL.Vec(IDL.Nat)],
      [Submission],
      [],
    ),
  'unpublishQuiz' : IDL.Func([QuizId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuizId = IDL.Nat;
  const Question = IDL.Record({
    'correctIndex' : IDL.Nat,
    'prompt' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QuizStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Quiz = IDL.Record({
    'id' : QuizId,
    'status' : QuizStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'questions' : IDL.Vec(Question),
  });
  const QuestionOutput = IDL.Record({
    'prompt' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Timestamp = IDL.Int;
  const Submission = IDL.Record({
    'answers' : IDL.Vec(IDL.Nat),
    'participantName' : IDL.Text,
    'score' : IDL.Nat,
    'correctAnswers' : IDL.Vec(IDL.Nat),
    'timestamp' : Timestamp,
    'quizId' : QuizId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestion' : IDL.Func([QuizId, Question], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createQuiz' : IDL.Func([IDL.Text, IDL.Text], [QuizId], []),
    'deleteQuiz' : IDL.Func([QuizId], [], []),
    'getAllQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPublishedQuizzes' : IDL.Func([], [IDL.Vec(QuizId)], ['query']),
    'getQuiz' : IDL.Func([QuizId], [Quiz], ['query']),
    'getQuizForTaking' : IDL.Func(
        [QuizId],
        [IDL.Vec(QuestionOutput)],
        ['query'],
      ),
    'getQuizSubmissions' : IDL.Func([QuizId], [IDL.Vec(Submission)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishQuiz' : IDL.Func([QuizId], [], []),
    'submitAnswers' : IDL.Func(
        [IDL.Text, QuizId, IDL.Vec(IDL.Nat)],
        [Submission],
        [],
      ),
    'unpublishQuiz' : IDL.Func([QuizId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };