/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Question {
  'correctIndex' : bigint,
  'prompt' : string,
  'options' : Array<string>,
}
export interface QuestionOutput { 'prompt' : string, 'options' : Array<string> }
export interface Quiz {
  'id' : QuizId,
  'status' : QuizStatus,
  'title' : string,
  'description' : string,
  'questions' : Array<Question>,
}
export type QuizId = bigint;
export type QuizStatus = { 'published' : null } |
  { 'draft' : null };
export interface Submission {
  'answers' : Array<bigint>,
  'participantName' : string,
  'score' : bigint,
  'correctAnswers' : Array<bigint>,
  'timestamp' : Timestamp,
  'quizId' : QuizId,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuestion' : ActorMethod<[QuizId, Question], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createQuiz' : ActorMethod<[string, string], QuizId>,
  'deleteQuiz' : ActorMethod<[QuizId], undefined>,
  'getAllQuizzes' : ActorMethod<[], Array<Quiz>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPublishedQuizzes' : ActorMethod<[], Array<QuizId>>,
  'getQuiz' : ActorMethod<[QuizId], Quiz>,
  'getQuizForTaking' : ActorMethod<[QuizId], Array<QuestionOutput>>,
  'getQuizSubmissions' : ActorMethod<[QuizId], Array<Submission>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishQuiz' : ActorMethod<[QuizId], undefined>,
  'submitAnswers' : ActorMethod<[string, QuizId, Array<bigint>], Submission>,
  'unpublishQuiz' : ActorMethod<[QuizId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];